server:
  port: 8082

spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessactivitity
      database: fitnessactivitity

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/